;PROGRAM TO ADD TWO 16 BIT NUMBERS
;GPR=GENERAL PURPOSE REGISTER 
MOV [1234H],1109H;   DATA TRANSFER TO MEMORY LOCATION
MOV [1334H],1345H;   DATA TRANSFER TO MEMORY LOCATION
MOV AX,[1234H];      COPY DATA TO GPR
MOV BX,[1334H];      COPY DATA TO GPR
ADD AX,BX;           ADDITION OF TEO NUMBER IS STORED IN AL