;addition of two 8 bits numbers
;GPR=GENERAL PURPOSE REGISTER
MOV [1100H],01H;  MOVE DATA IN A MEMORY LOCATION
MOV AL,[1100H];   COPY DATA FROM MEMORY LOCATION TO GPR , DATA CAN DIRECTLY BE MOVED TO GPR BUT GPR ARE FOR TEMPORARY USE ONLY
MOV [1220H],0EH;  MOVE DATA TO MEMORY LOCATION
MOV BL,[1220H];   COPY DATA FROM MEMORY LOCATION TO GPR
ADD AL,BL;        THE RESULT OF ADDITION OF AL AND BL WILL BE STORED IN AL
