;program to subtract two 16 bits data 
MOV CX,1458H;  TRANSFER DATA TO GPR
MOV DX,0F44H;  TRANSFER DATA TO GPR
SUB CX,DX;     SUBTRACT DATA OF DX FROM DX AND STORE IT IN CX
SUB DX,CX;     SUBTRACT DATA OF CX FROM DX AND STORE IT IN DX